/**
 * financial-field-catalog-cdkt.ts
 * Catalog fields cho nhóm CĐKT (Bảng cân đối kế toán — Balance Sheet Analysis).
 */

import type { FieldCatalogItem } from "@/lib/report/config-schema";

export const CATALOG_CDKT: FieldCatalogItem[] = [
  {
    field_key: "B.financial.cdkt.assets_current",
    label_vi: "Phân tích Tài sản ngắn hạn",
    group: "B.financial.cdkt",
    type: "text",
    required: true,
    examples: [],
    analysis_prompt: [
      "Phân tích tình hình Tài sản ngắn hạn (mã số 100) trong Bảng cân đối kế toán.",
      "Từ bảng CĐKT đã cung cấp, hãy:",
      "1. So sánh tổng TSNH năm hiện tại vs năm trước: nêu mức tăng/giảm tuyệt đối (triệu/tỷ đồng) và tỷ lệ %.",
      "2. Phân tích từng thành phần chính:",
      "   - Tiền và tương đương tiền (mã số 110): xu hướng tăng/giảm, tỷ trọng trong TSNH.",
      "   - Phải thu khách hàng (mã số 130-131): xu hướng, đánh giá chất lượng công nợ phải thu.",
      "   - Hàng tồn kho (mã số 140): xu hướng tăng/giảm, tỷ trọng HTK/TSNH — có hợp lý với ngành không?",
      "   - TSNH khác (mã số 150): nếu có biến động đáng kể.",
      "3. Tỷ trọng TSNH trong Tổng tài sản (mã số 270): cơ cấu có phù hợp đặc thù ngành không?",
      "4. Từ góc nhìn người cho vay: TSNH có đủ đảm bảo nghĩa vụ nợ ngắn hạn không?",
      "Ưu tiên tìm điểm tích cực; nếu có rủi ro (HTK cao, phải thu khó đòi), đề xuất giải pháp cụ thể.",
    ].join(" "),
  },
  {
    field_key: "B.financial.cdkt.assets_noncurrent",
    label_vi: "Phân tích Tài sản dài hạn",
    group: "B.financial.cdkt",
    type: "text",
    required: true,
    examples: [],
    analysis_prompt: [
      "Phân tích tình hình Tài sản dài hạn (mã số 200) trong Bảng cân đối kế toán.",
      "1. So sánh tổng TSDH năm hiện tại vs năm trước: mức tăng/giảm tuyệt đối và %.",
      "2. Phân tích thành phần chính:",
      "   - Tài sản cố định (mã số 220): xu hướng đầu tư TSCĐ, nguyên giá vs khấu hao lũy kế.",
      "   - Đầu tư tài chính dài hạn (mã số 250, nếu có): quy mô và xu hướng.",
      "   - TSDH khác (mã số 260, nếu có).",
      "3. Tỷ trọng TSDH trong Tổng tài sản: cơ cấu có phù hợp đặc thù ngành?",
      "4. Đánh giá năng lực sản xuất kinh doanh dựa trên quy mô TSCĐ.",
      "Nêu điểm tích cực về năng lực cơ sở vật chất; nếu TSCĐ giảm do khấu hao, đánh giá tính hợp lý.",
    ].join(" "),
  },
  {
    field_key: "B.financial.cdkt.liabilities",
    label_vi: "Phân tích Nợ phải trả",
    group: "B.financial.cdkt",
    type: "text",
    required: true,
    examples: [],
    analysis_prompt: [
      "Phân tích tình hình Nợ phải trả (mã số 300) trong Bảng cân đối kế toán.",
      "1. So sánh tổng Nợ phải trả năm hiện tại vs năm trước: tăng/giảm tuyệt đối và %.",
      "2. Phân tích cơ cấu nợ:",
      "   - Nợ ngắn hạn (mã số 310): vay ngắn hạn ngân hàng, phải trả người bán, thuế phải nộp...",
      "   - Nợ dài hạn (mã số 330): vay dài hạn, nếu có.",
      "3. Tỷ lệ Nợ/Tổng tài sản và Nợ/VCSH: đòn bẩy tài chính ở mức nào?",
      "4. Mức độ phụ thuộc vay nợ: xu hướng tăng hay giảm?",
      "5. Từ góc nhìn người cho vay: mức nợ có an toàn không? TSNH có đủ đảm bảo Nợ NH không?",
      "Nếu nợ tăng, phân biệt: do mở rộng SXKD (tích cực) hay do thua lỗ/mất cân đối (tiêu cực).",
      "Đề xuất giải pháp nếu đòn bẩy quá cao.",
    ].join(" "),
  },
  {
    field_key: "B.financial.cdkt.equity",
    label_vi: "Phân tích Vốn chủ sở hữu",
    group: "B.financial.cdkt",
    type: "text",
    required: true,
    examples: [],
    analysis_prompt: [
      "Phân tích tình hình Vốn chủ sở hữu (mã số 400) trong Bảng cân đối kế toán.",
      "1. So sánh VCSH năm hiện tại vs năm trước: tăng/giảm tuyệt đối và %.",
      "2. Phân tích cơ cấu VCSH:",
      "   - Vốn đầu tư của chủ sở hữu / Vốn điều lệ (mã số 411): ổn định hay thay đổi?",
      "   - Lợi nhuận sau thuế chưa phân phối (mã số 421): xu hướng tích lũy.",
      "3. Hệ số tự tài trợ (VCSH/Tổng TS): DN có phụ thuộc vay nợ quá mức không?",
      "4. Tăng trưởng VCSH chủ yếu từ đâu: bổ sung vốn hay tích lũy lợi nhuận?",
      "5. Khả năng tài chính nội tại: VCSH dày = nền tảng vững chắc cho hoạt động vay vốn.",
      "Ưu tiên điểm tích cực về sự tăng trưởng VCSH và khả năng tự tài trợ.",
    ].join(" "),
  },
  {
    field_key: "B.financial.cdkt.summary",
    label_vi: "Tổng kết phân tích Bảng CĐKT",
    group: "B.financial.cdkt",
    type: "text",
    required: true,
    examples: [],
    analysis_prompt: [
      "Tổng kết phân tích Bảng cân đối kế toán.",
      "Dựa trên toàn bộ dữ liệu CĐKT đã phân tích, viết tóm tắt 4-6 câu bao gồm:",
      "1. Quy mô tổng tài sản và xu hướng tăng trưởng.",
      "2. Cơ cấu tài sản (TSNH vs TSDH) và nguồn vốn (Nợ vs VCSH): có cân đối hợp lý không?",
      "3. Điểm mạnh và điểm yếu chính trong cấu trúc tài chính.",
      "4. Kết luận từ góc nhìn người cho vay: bảng CĐKT có tạo cơ sở tốt để cho vay không?",
    ].join(" "),
  },
];
