import type { Metadata } from "next";

import { LanguageProvider } from "@/components/language-provider";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

// Fallback fonts for offline/restricted environments
// In production, consider using local font files via @font-face
const fontVariables = {
  inter: "--font-inter",
  geistSans: "--font-geist-sans",
  geistMono: "--font-geist-mono",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Apply dark class before first paint — prevents flash of wrong theme */}
        <script
          dangerouslySetInnerHTML={{
            __html: `try{const t=localStorage.getItem('app_theme');const d=t==='dark'||(t==='system'||!t)&&window.matchMedia('(prefers-color-scheme: dark)').matches;if(d)document.documentElement.classList.add('dark');}catch{}`,
          }}
        />
        {/* CSS variables for font fallbacks */}
        <style>{`
          :root {
            --font-inter: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            --font-geist-sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            --font-geist-mono: 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace;
          }
        `}</style>
      </head>
      <body className="antialiased">
        <ThemeProvider>
          <LanguageProvider>{children}</LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
